/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as pagesTestMdxIndexRouteImport } from './routes/(pages)/test-mdx/index'
import { Route as pageslandingIndexRouteImport } from './routes/(pages)/(landing)/index'

const pagesTestMdxIndexRoute = pagesTestMdxIndexRouteImport.update({
  id: '/(pages)/test-mdx/',
  path: '/test-mdx/',
  getParentRoute: () => rootRouteImport,
} as any)
const pageslandingIndexRoute = pageslandingIndexRouteImport.update({
  id: '/(pages)/(landing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof pageslandingIndexRoute
  '/test-mdx/': typeof pagesTestMdxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof pageslandingIndexRoute
  '/test-mdx': typeof pagesTestMdxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(pages)/(landing)/': typeof pageslandingIndexRoute
  '/(pages)/test-mdx/': typeof pagesTestMdxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test-mdx/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test-mdx'
  id: '__root__' | '/(pages)/(landing)/' | '/(pages)/test-mdx/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  pageslandingIndexRoute: typeof pageslandingIndexRoute
  pagesTestMdxIndexRoute: typeof pagesTestMdxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(pages)/test-mdx/': {
      id: '/(pages)/test-mdx/'
      path: '/test-mdx'
      fullPath: '/test-mdx/'
      preLoaderRoute: typeof pagesTestMdxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/(landing)/': {
      id: '/(pages)/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof pageslandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  pageslandingIndexRoute: pageslandingIndexRoute,
  pagesTestMdxIndexRoute: pagesTestMdxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
