/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as pageslandingIndexRouteImport } from './routes/(pages)/(landing)/index'
import { Route as pagesCategoryIndexRouteImport } from './routes/(pages)/$category/index'
import { Route as pagesCategorySlugIndexRouteImport } from './routes/(pages)/$category/$slug/index'

const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const pageslandingIndexRoute = pageslandingIndexRouteImport.update({
  id: '/(pages)/(landing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesCategoryIndexRoute = pagesCategoryIndexRouteImport.update({
  id: '/(pages)/$category/',
  path: '/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesCategorySlugIndexRoute = pagesCategorySlugIndexRouteImport.update({
  id: '/(pages)/$category/$slug/',
  path: '/$category/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/analytics': typeof ApiAnalyticsRoute
  '/$category/': typeof pagesCategoryIndexRoute
  '/': typeof pageslandingIndexRoute
  '/$category/$slug/': typeof pagesCategorySlugIndexRoute
}
export interface FileRoutesByTo {
  '/api/analytics': typeof ApiAnalyticsRoute
  '/$category': typeof pagesCategoryIndexRoute
  '/': typeof pageslandingIndexRoute
  '/$category/$slug': typeof pagesCategorySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/analytics': typeof ApiAnalyticsRoute
  '/(pages)/$category/': typeof pagesCategoryIndexRoute
  '/(pages)/(landing)/': typeof pageslandingIndexRoute
  '/(pages)/$category/$slug/': typeof pagesCategorySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/analytics' | '/$category/' | '/' | '/$category/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/analytics' | '/$category' | '/' | '/$category/$slug'
  id:
    | '__root__'
    | '/api/analytics'
    | '/(pages)/$category/'
    | '/(pages)/(landing)/'
    | '/(pages)/$category/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  pagesCategoryIndexRoute: typeof pagesCategoryIndexRoute
  pageslandingIndexRoute: typeof pageslandingIndexRoute
  pagesCategorySlugIndexRoute: typeof pagesCategorySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/(landing)/': {
      id: '/(pages)/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof pageslandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/$category/': {
      id: '/(pages)/$category/'
      path: '/$category'
      fullPath: '/$category/'
      preLoaderRoute: typeof pagesCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/$category/$slug/': {
      id: '/(pages)/$category/$slug/'
      path: '/$category/$slug'
      fullPath: '/$category/$slug/'
      preLoaderRoute: typeof pagesCategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  pagesCategoryIndexRoute: pagesCategoryIndexRoute,
  pageslandingIndexRoute: pageslandingIndexRoute,
  pagesCategorySlugIndexRoute: pagesCategorySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
